### ISSUE TITLE
We need to set up email accounts for the convergencemp.org domain

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#10]
bryan@
info@
support@

**Comment by debdiproy** [comment]
Webmail access: http://convergencemp.com/webmail

User: 
bryan@convergencemp.com
info@convergencemp.com
support@convergencemp.com

Pass: cmp2016!

**Comment by Designer-cleonix** [comment]
@camerontrimble  Hello, 
All are working fine. Please check the mail id s and let me know if you need some other mail id.

**Comment by camerontrimble** [comment]
I am working on this. You can take it off your list but I want to leave it in Github so that I don't forget.

**Comment by Designer-cleonix** [comment]
Ok. No problem.

**Comment by camerontrimble** [comment]
I will need help getting the gmail email accounts set up because the domain is pointing to the cleonix servers. 
![screenshot 2016-05-18 22 51 19](https://cloud.githubusercontent.com/assets/15096099/15381172/29248ac8-1d4b-11e6-8116-29399b12cecf.png)

**Comment by Designer-cleonix** [comment]
@debdiproy  Please have a look.

**Comment by debdiproy** [comment]
Give me the access to this gmail account  **in email** and I will configure this.
