### ISSUE TITLE
Please add "My Account" page and link it to the main menu

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/Convergence-Music-Project#108]

**Comment by bikash02** [comment]
sidebar menu should be:
   1.Account Dashboard 
   2.Account Information  
   3.My Orders  
   4.My Product Reviews  
   5.My Downloadable Products

**Comment by debajyotiGuha** [comment]
Sir,
Done
On Tuesday 24 May 2016 05:31 PM, Bikash Hutait wrote:

> sidebar menu should be:
> 1.Account Dashboard
> 2.Account Information
> 
> 3.My Orders
> 
> 4.My Product Reviews
> 
> 5.My Downloadable Products
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub 
> https://github.com/ConvergenceUS/Convergence-Music-Project/issues/108#issuecomment-221247559

## 

Thanks and Regards
Debajyoti Guha
debajyoti@cleonix.net

**Comment by bikash02** [comment]
Please complete the below point
5.My Downloadable Products

**Comment by bikash02** [comment]
Please add the "ORDER" module in the backoffice

**Comment by bikash02** [comment]
@camerontrimble  Please check the modules "My Account"  in the frontend and "Orders" in the backend.Please tell me if you need more in this sections.

**Comment by camerontrimble** [comment]
on http://convergencemp.com/user_profile_update.php, Add the fields - All should be OPTIONAL.

Address
Address (apt #, suite #, etc.)
City
State
Zip Code
Mobile Phone
Organization Name

**Comment by bikash02** [comment]
updated..
