### ISSUE TITLE
Cart price is not pulling the correct pricing

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#110]
Test using the bundle price.

**Comment by bikash02** [comment]
@debajyotiGuha Please update the issue by tomorrow.

**Comment by bikash02** [comment]
@debdiproy We are waiting for your final feedback regarding the issue.

**Comment by camerontrimble** [comment]
Pricing is not correct. If the choose the bundle, it should just pull the single bundle price.

**Comment by bikash02** [comment]
updated the cart.Please check once again.
