### ISSUE TITLE
Add filters for rating and top 5 purchased products (best sellers) on the left filter on Find a Song page

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#111]

**Comment by bikash02** [comment]
@ i-puspita Please update the sidebar design for rating and top 5 purchased

**Comment by i-puspita** [comment]
updated

**Comment by bikash02** [comment]
We have added the filters.Kindly check on find a Song page.

**Comment by camerontrimble** [comment]
Looks great! Why is there a category list at the bottom? Feels like a repeat of what we have above.
