### ISSUE TITLE
Tried to add a new blog post and got this error

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#113]
![screenshot 2016-05-28 14 36 59](https://cloud.githubusercontent.com/assets/15096099/15629234/b915852c-24e1-11e6-97da-70c36fa3c89a.png)

**Comment by bikash02** [comment]
resolved the issue.

**Comment by camerontrimble** [comment]
Still not working for me

**Comment by camerontrimble** [comment]
I just figured it out. We need to allow " ' " in the Blog Titles. I was trying to type "It's Time for a New Song". When I changed it to "Its Time For a New Song" it went through.

**Comment by camerontrimble** [comment]
When I go in to edit the post, the text doesn't appear in the editor. We also need to add a short description to the blog section so that some text appears on the front end of the site.

**Comment by camerontrimble** [comment]
When I add text to the blog for the first time, it doesn't stick. When I go back in to edit it (re-paste it), It does stick. Please review.

**Comment by bikash02** [comment]
Thank you @camerontrimble.
updated the code.
