### ISSUE TITLE
Style the songs catalog

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#116]
Can you remove some of the white space?

![screenshot 2016-05-31 10 46 43](https://cloud.githubusercontent.com/assets/15096099/15679234/17d8f082-271f-11e6-9ec1-b5df9a65c806.png)

**Comment by i-puspita** [comment]
Songs catalog page style is updated. Please check the page.

**Comment by bikash02** [comment]
Removed the white space from the catalog page
