### ISSUE TITLE
Placeholder in Music Submit box that says "Name" where they type their name

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#121]

**Comment by bikash02** [comment]
updated the placeholder

**Comment by camerontrimble** [comment]
![screenshot 2016-06-01 09 50 13](https://cloud.githubusercontent.com/assets/15096099/15711953/4b2ba852-27de-11e6-9923-42bd1ac6bc54.png)

It needs to be by the white line where the curser is
