### ISSUE TITLE
What happened to this page? http://convergencemp.com/profile.php

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#128]

**Comment by bikash02** [comment]
As per my knowledge someone delete the team members data.

**Comment by bikash02** [comment]
I apologize for this and in the future we will be more careful.We won't let that happen again.But our developer said that Its may be from your side.So please check the administrative account and delete if there were any unwanted accounts in the backoffice.

We have already cloned the website in our test server and from now we will test and debug in development server and once we will get approve we will migrate to the live server.
