### ISSUE TITLE
Install preview feature for downloadables

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#13]

**Comment by bikash02** [comment]
updated
http://convergencemp.com/backoffice/product_edit.php?id=20

**Comment by camerontrimble** [comment]
I added this to the new table design. The customer needs to be able to preview the products.

**Comment by bikash02** [comment]
Do you want to preview in the same page like modal view or in a new page?We are very close to finish the issue.You will get the update by tomorrow.

**Comment by camerontrimble** [comment]
Modal view. You will need to add preview fields to the backend and we will upload files there.

**Comment by bikash02** [comment]
updated the issue.please check the below link
http://convergencemp.com/product-details.php?post=20

**Comment by bikash02** [comment]
We have added a limit on music file preview.User can play the music file only for 5seconds.

**Comment by camerontrimble** [comment]
Lets make the audio file play for 30 seconds.  The lead sheet and piano arrangement are shown in their entirety and this in effect gives these items away.  We should only show a half page or something like that for the preview.

**Comment by bikash02** [comment]
updated.
