### ISSUE TITLE
Automatic email generated when someone buys a membership

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#132]
Bryan is going to provide text

Email needs to have a custom promo code that allows free downloads

**Comment by bikash02** [comment]
Can you please tell me what exactly you need in this section?I just wondering how much products  they will able able to download and how much time they will get those free download.

Will it be fine if we'll create a custom promo code and added some products  in it and particular that products will be free downloaded when someone buy a membership.
