### ISSUE TITLE
I want to be able to see how many specifically products we have sold

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#135]

**Comment by camerontrimble** [comment]
For example, we want to produce a list of the people who have purchased memberships and export them.

**Comment by bikash02** [comment]
We have added the link to the menu "Product Sold Out"

**Comment by camerontrimble** [comment]
I need to be able to pull a report BY PRODUCTS, not orders. I want to see how many of a product have been sold, who bought the products and when. I want to be able to sort by product name, date, customer name/id.

**Comment by camerontrimble** [comment]
We still can't run a report based on products. It seems like the "Order Details" and "Products Sold Out" are showing the same information. I want to be able to see how many times we sold a specific song, or membership, or lead sheet.

**Comment by bikash02** [comment]
Please check the "Reports" module.
https://www.convergencemp.com/backoffice/product-report.php

Working on the membership report and will update you soon.

**Comment by bikash02** [comment]
Please check the report section
