### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#139]
I just received several new songs through our “Submit” tab.  I see them on the backoffice of the site fine, but I should be receiving an email message with the Mp3 and the lyric sheet attached and contact info of who sent the song.  I have not received that either on this email address or on the bryan@convergencemp.com  email.  Let’s please get this working properly sooner than later so I will know when songs are sent and have the easiest and quickest way to access them and share them with other song evaluators.

Also, I think it would be good to send a confirmation message to people once they have uploaded a song correctly so they won’t be wondering.  The last person to upload songs contacted me and said he wasn’t sure if they went through or not and that he was looking for some verification that they did.  

Thanks,

Bryan

**Comment by bikash02** [comment]
updated
