### ISSUE TITLE
Test creating a user account - doesn't seem to be working

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#14]

**Comment by jayantapatra** [comment]
Corrected this issue 

admin access
username : bubai
password : bubai2das

user access 
username : jayanta
password : 12341

**Comment by camerontrimble** [comment]
I am not able to create new accounts on the site. Can you check this?

**Comment by bikash02** [comment]
Updated the code.Kindly check once again.
