### ISSUE TITLE
The site is not displaying well on iPad or iPhone

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#140]

**Comment by Designer-cleonix** [comment]
@i-puspita Solve this ASAP

**Comment by i-puspita** [comment]
The following link( http://convergencemp.com/) is updated. Kindly check this & give us your feedback.

**Comment by camerontrimble** [comment]
We now have some menu issues
![img_0036](https://cloud.githubusercontent.com/assets/15096099/17559170/2831aace-5eeb-11e6-8f14-0fe90aaf9ff5.PNG)

**Comment by Designer-cleonix** [comment]
@i-puspita  RESOLVE IT ASAP.

**Comment by i-puspita** [comment]
updated
