### ISSUE TITLE
Weird < in the menu

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#151]
![screen shot 2016-08-08 at 10 25 11 am](https://cloud.githubusercontent.com/assets/15096099/17483049/8182fe88-5d52-11e6-9b4c-bd2a681c1320.png)

**Comment by Designer-cleonix** [comment]
@i-puspita  Please take care of this.

**Comment by i-puspita** [comment]
Updated.Please Check this.
