### ISSUE TITLE
Need to be able to BUY the membership when you click on the early Adopter button

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#152]
Right now it directs to this page (and it should NOT): http://convergencemp.com/subscription-service.php

![screen shot 2016-08-10 at 11 16 21 am](https://cloud.githubusercontent.com/assets/15096099/17559363/f9a524e6-5eeb-11e6-94d1-b5da20f0b9bf.png)

**Comment by debdiproy** [comment]
Completed
