### ISSUE TITLE
Make advanced integration of Paypal so that customers do not leave the site.

### ISSUE THREAD

**Issue by debdiproy** [ConvergenceUS/Convergence-Music-Project#156]

**Comment by bikash02** [comment]
@creating-bubai  Please give an update on it.

**Comment by bikash02** [comment]
@camerontrimble Please provide us the below credentials for advance paypal integration {Using Credit Card}.
1.API login ID
2.API password
3.API signature

Do you really want to integrate stripe in the system? I will integrate this on the development server using a test or developer account if you need.

**Comment by bikash02** [comment]
If it is possible then please send those three info for **live and sandbox**  as well.

**Comment by bikash02** [comment]
We have completed the advance paypal integration.
http://cleonix.biz/convergencemp/product-details.php?post=291
Waiting for your approval to push in the live server.

Note: We already tested from our ends.

**Comment by camerontrimble** [comment]
The dropdown menu with the states listed has weird fields in it. Some of these are not US States...

![screen shot 2016-10-19 at 10 48 20 am](https://cloud.githubusercontent.com/assets/15096099/19523838/bd26114e-95e9-11e6-8191-ed4fcb8bf564.png)

**Comment by camerontrimble** [comment]
There are a LOT of clicks that you have to make to get to the page you can finally make a payment. Is there any way to shorten that process? 

You have to click Proceed from the Cart page, then Check Out, then register as a user, then click proceed again, then press check out AGAIN, then and then you FINALLY get to the payment page. 

That is just too much.

**Comment by bikash02** [comment]
@creating-bubai @debajyotiGuha @i-puspita  Please fix the issue by today.
Cut down the steps to get the payment page more easier and make it simple.If you need anything else from me don't be hesitate to ask.

**Comment by Designer-cleonix** [comment]
Design section is updated

**Comment by i-puspita** [comment]
design section is updated

**Comment by debajyotiGuha** [comment]
I have moved on the development phase and just very close to finish.I will complete it by tomorrow.There are lots of code we have to put in a single page like magento or woocommerce checkout page.In the cart page only products added in cart will be visable and then in the checkout page all the functionalities after place a order will be performed. ie, “register or login” , then “review order” and “make payment”.

Will update you very soon...

![screenshot-s28 postimg org 2016-10-20 21-11-38](https://cloud.githubusercontent.com/assets/18532725/19567521/9bd3f2b8-970b-11e6-8600-9d7fd27df489.png)

**Comment by debajyotiGuha** [comment]
The dropdown menu with the states list corrected.

**Comment by bikash02** [comment]
@camerontrimble  please check the layout and functionalities.Its now in the development server.Once you approve we'll migrate the files to live server.
http://cleonix.biz/convergencemp/product-listing.php

**Comment by camerontrimble** [comment]
Approved and pushed to live
