### ISSUE TITLE
Add click desk chat

### ISSUE THREAD

**Issue by debdiproy** [ConvergenceUS/Convergence-Music-Project#162]

**Comment by camerontrimble** [comment]
<script type='text/javascript'>
var _glc =_glc || []; _glc.push('all_ag9zfmNsaWNrZGVza2NoYXRyDgsSBXVzZXJzGMKV4wcM');
var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' : 
'http://my.clickdesk.com/clickdesk-ui/browser/');
var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
var glcspt = document.createElement('script'); glcspt.type = 'text/javascript'; 
glcspt.async = true; glcspt.src = glcpath + 'livechat-new.js';
var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(glcspt, s);
</script>

**Comment by camerontrimble** [comment]
Emailed to Debdip

**Comment by bikash02** [comment]
Added the click desk chat.
