### ISSUE TITLE
Security warning that will drive customers away

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#173]
![screen shot 2016-08-26 at 9 55 45 am](https://cloud.githubusercontent.com/assets/15096099/18007772/6eb061ae-6b73-11e6-9c0c-7a023edabefb.png)

**Comment by bikash02** [comment]
Currently the website don't have any active SSL.You are getting the security warning due to returning https(paypal) to http(cmp) website.

**Comment by camerontrimble** [comment]
Please buy one, install it and bill me

**Comment by camerontrimble** [comment]
Is this installed?

**Comment by bikash02** [comment]
SSL activated.
