### ISSUE TITLE
Add a blog to the site

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#18]

**Comment by Designer-cleonix** [comment]
We have created  blog list and blog details pages for the site.
http://convergencemp.com/blog.php
http://convergencemp.com/blog-detail.php?post=9

And add the link in the header menu.

Please have a look.

**Comment by bikash02** [comment]
updated the comment section as well and once you will approve the comment from the admin panel,it will show in the website.Added the social share button.
