### ISSUE TITLE
Please add counter button to sidebar menu in the backoffice

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/Convergence-Music-Project#184]
Add button counter to the below menus.
1.Orders  | display as "Complete" data count.
2. Comments | display as "Pending" data count.
3. Reviews & ratings  |  display as "Pending" data count.

**Comment by creating-bubai** [comment]
Updated. Please check @bikash02

**Comment by bikash02** [comment]
Please update the circle alignment and make it looks better.

**Comment by i-puspita** [comment]
updated

**Comment by bikash02** [comment]
@camerontrimble  please check the backoffice sidebar menu.We have updated it to the wordpress structure like order & comments.

**Comment by camerontrimble** [comment]
NICELY DONE!!!!!!! This looks great!
