### ISSUE TITLE
Membership expire date

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/Convergence-Music-Project#185]

**Comment by bikash02** [comment]
Is there any renewal option for membership user or it's one time membership?Can the EAM user renew membership after it expires?Please keep me update.

**Comment by camerontrimble** [comment]
They should have the option to renew. The EAM will need to be billed at a higher rate in the second year. We can manually enter a different price if that makes life easier. We DON'T want them to have to sign up again.

**Comment by bikash02** [comment]
What will be the amount for 2nd year?Is it same amount for all eam user or you want to set different rate for individual user.

**Comment by camerontrimble** [comment]
$249

**Comment by bikash02** [comment]
okay thanks.

**Comment by bikash02** [comment]
updated.

**Comment by bikash02** [comment]
updated.
