### ISSUE TITLE
Urgent issue!!!! Regarding product viewing

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#187]
Trying to see the Piano Arrangement previews on the Convergence Music Project and haven't hit one that will show me anything. A first-page PDF might be more helpful as there is no instruction other than to purchase before seeing it. I need to know if my people can play the arrangement before I'll purchase.

**Comment by creating-bubai** [comment]
Updated. Please check @bikash02
