### ISSUE TITLE
People are having trouble purchasing the early adopter membership

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#191]
When you click on the "Become an early adopter member" from the banner, it makes you register as a user. Then you get stuck in multiple screens of adding it to your cart. Then it gets stuck just processing and not going through.

**Comment by camerontrimble** [comment]
I think it should just take them straight to the cart so that they can check out immediately. This is the most important product they can purchase. Let's make it as simple as possible.

**Comment by creating-bubai** [comment]
updated. Please check @bikash02

**Comment by bikash02** [comment]
We have updated the page design as well.Here is the link
https://www.convergencemp.com/eam-new.php

After getting confirmation from your end we will make it live.

**Comment by camerontrimble** [comment]
Make it live. Thanks.

**Comment by bikash02** [comment]
updated.
https://www.convergencemp.com/eam.php

**Comment by bikash02** [comment]
updated to live server
