### ISSUE TITLE
Please update the email template

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/Convergence-Music-Project#192]
Make the email templates more professional & better look.

**Comment by bikash02** [comment]
@camerontrimble Please check the email template that we have designed.
https://www.convergencemp.com/email-template.html

Let me know if you want to add something else.

**Comment by bikash02** [comment]
"#" tag will be replaced by dynamically as per email subject and body.

**Comment by camerontrimble** [comment]
Looks great!
