### ISSUE TITLE
You can't access the cart from the mobile menu

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#193]

**Comment by debdiproy** [comment]
Debarati look into this urgently

**Comment by camerontrimble** [comment]
What is the update on this?

**Comment by i-puspita** [comment]
updated

**Comment by bikash02** [comment]
push to live server

**Comment by camerontrimble** [comment]
If pushed to live, please close @bikash02

**Comment by camerontrimble** [comment]
Actually, I just tested this. It isn't live yet. Note that we posted this issue 21 days ago. That is unacceptable.

**Comment by Designer-cleonix** [comment]
@bikash02 @debdiproy Please solve this ASAP.

**Comment by bikash02** [comment]
@camerontrimble please check the attached file.We have reached the cart page to mobile view and it was on the live server.
![screenshot_20161017-133331](https://cloud.githubusercontent.com/assets/16361011/19468486/31b81cde-9534-11e6-85b1-e7a42f442978.jpg)

If you send me a screen shot it will be helpful.

**Comment by camerontrimble** [comment]
I still can't see it. I'm using safari on my iPhone. Also note that the logo is too small on the mobile view. ![](http://i.imgur.com/g8F4nZ3.jpg)

**Comment by camerontrimble** [comment]
I should also note that I have four products in my cart...so I should see the cart button.

**Comment by bikash02** [comment]
@i-puspita please check and update the mobile menu asap.

**Comment by bikash02** [comment]
@debdiproy Please talk to @camerontrimble regarding the issue.Here is a scroller in the mobile menu but the user not aware of it.So they faced the problem to access the cart page when they were trying.
http://cleonix.biz/convergencemp/product-listing.php

**Comment by camerontrimble** [comment]
Hide "About" and "Submit" from the mobile view

**Comment by bikash02** [comment]
@i-puspita please update the mobile menu

**Comment by i-puspita** [comment]
Mobile Menu is updated in http://cleonix.biz/convergencemp/
Please check

**Comment by camerontrimble** [comment]
Push to live and close this issue
