### ISSUE TITLE
Bug in the blog posting module

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#194]
I just tried to post a blog. I added the text into the editor and pressed submit. The post appeared but was missing the body that I posted in the editor. The title, image and category showed up. But to body content. 

Then I edited the post, repasting the text into the body editor. This time it went through. 

Please test.

**Comment by creating-bubai** [comment]
Updated at test server. Please check @debdiproy and @bikash02 
Test server Link:     http://cleonix.biz/convergencemp/backoffice/post-add.php

**Comment by bikash02** [comment]
updated to live server
