### ISSUE TITLE
Add text to automatic email sent when someone submits a song

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#195]
In addition to sending the form that we are already sending song submitters, add the following text first:

Thanks for submitting your song to be part of the CMP catalog.  Our review team will listen soon and get back to you within 2 weeks.

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02

**Comment by bikash02** [comment]
push to live server.

**Comment by camerontrimble** [comment]
Was this pushed to live? If so, please close @bikash02

**Comment by bikash02** [comment]
updated
