### ISSUE TITLE
Add column with name, date, and email of person who submits song to back office 

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#198]
I would like to be able to look at the product description list on the back office and know the who has submitted a song, the date, and their email so that I can easily identify the songs and reach the songwriter on email.

**Comment by creating-bubai** [comment]
Updated. Please check @debdiproy @bikash02 .
Test server link:  http://cleonix.biz/convergencemp/backoffice/product-view.php

**Comment by bikash02** [comment]
updated to live server
