### ISSUE TITLE
Search box on home page does not work for Artist Name

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#199]
We need to include the artist's name in the search functions on the home page.  Or, we need to identify how the search works.  For example, "Search by topic"  or "Search by Song title"

**Comment by creating-bubai** [comment]
Updated.Please check @bikash02 @debdiproy .
Search using product name or product category.
Test server link:  
http://cleonix.biz/convergencemp
http://cleonix.biz/convergencemp/product-listing.php
http://cleonix.biz/convergencemp/product-search.php
http://cleonix.biz/convergencemp/menu.php

**Comment by camerontrimble** [comment]
Push to live

**Comment by bikash02** [comment]
uploaded the files to live server.
