### ISSUE TITLE
Change product name of Early Adopter Membership in backoffice

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#200]
The product name for the Early Adopter Membership in the backoffice comes up as "Churches 399 members or less."  It should say Early Adopter Membership.  When we start the annual membership on Jan. 1, 2017 then there will be the two different size memberships.

**Comment by creating-bubai** [comment]
Updated in front-end and back-end. Please check @debdiproy @bikash02 .

Test server Link:  
http://cleonix.biz/convergencemp/subscribe.php
http://cleonix.biz/convergencemp/backoffice/order-details.php

**Comment by bikash02** [comment]
updated to live server.
