### ISSUE TITLE
Make it possible to choose a custom name for a promo code

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#201]
Debdip and I discussed this.  Now the codes are random numbers and letters that will be hard for people to remember.  We want to be able to make up our own name to use so that it is easy for people to remember and use the code.

**Comment by creating-bubai** [comment]
Updated. Please check @debdiproy @bikash02 .

Test server link:  
http://cleonix.biz/convergencemp/backoffice/coupon-add.php
http://cleonix.biz/convergencemp/backoffice/coupon-edit.php
Note: You must enter 8 digit into coupon code input section (maximum and minimum text length of this field is 8)

**Comment by bikash02** [comment]
uploaded the files to live
