### ISSUE TITLE
Early Adopter members login info not working

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#203]
A person who has attempted to purchase the Early Adopter Membership emailed me and said that when they attempt to use the login info they were sent the site keeps sending them back to purchase the Early Adopter membership which they say they have already purchased.

**Comment by creating-bubai** [comment]
Updated. Please check @debdiproy @bikash02 .

Test server link:  
http://cleonix.biz/convergencemp/eam.php
http://cleonix.biz/convergencemp/cart.php

**Comment by camerontrimble** [comment]
Approved. Please push to live.

**Comment by bikash02** [comment]
updated to live server.
