### ISSUE TITLE
Error alert

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#204]
![img_4606](https://cloud.githubusercontent.com/assets/15096099/18819760/7eb69326-8364-11e6-90bc-2307c0771f5a.PNG)

**Comment by Designer-cleonix** [comment]
@creating-bubai  UPDATE IT.

**Comment by creating-bubai** [comment]
Updated. Please check in your mobile @debdiproy @bikash02 @Designer-cleonix 

Test sever link:  http://cleonix.biz/convergencemp/product-listing.php

**Comment by bikash02** [comment]
Uploaded the file to live server.
