### ISSUE TITLE
Sales in Backoffice are still marked pending

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#206]
Almost all of the attempted sales are marked pending and not completed.  You have suggested this is a problem with PayPal not completing the process somehow.  Please resolve this immediately!

**Comment by Designer-cleonix** [comment]
@bikash02 Please do the needful.

**Comment by bikash02** [comment]
@BryanCMP  Please response to #207 issue and we'll take care the rest.

**Comment by bikash02** [comment]
The issue was resolved.
