### ISSUE TITLE
Edits to http://convergencemp.com/profile.php

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#21]
Change the page name to "Our Team" in the navigation and the page 

Connect the individual profiles to the backend so that we can add the bios

**Comment by i-puspita** [comment]
"Change the page name to "Our Team" in the navigation and the page" is updated.

**Comment by bikash02** [comment]
you can add or edit the team member from the backend
Sidebar Navigation -> Website Frontend -> Team Member
