### ISSUE TITLE
Fix spacing problem in some categories on front end of site

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#211]
The third category on the "Browse Categories" list, "Ethnic/Cultural Tradition" has a spacing problem between the words Cultural and Tradtion.  The same problem exists with the last category, "Written Word Liturgical Resources"   These extra spaces were included when the category was created in the back office.

**Comment by camerontrimble** [comment]
Make everything left justified

**Comment by i-puspita** [comment]
Updated in test site. Please check.

**Comment by bikash02** [comment]
@i-puspita please check the subcategories list under the main categories.Still having some formatting issues.Try to minimize it asap.

**Comment by i-puspita** [comment]
Updated. Please check.

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 
Test server link: http://cleonix.biz/convergencemp/product-listing.php
                          http://cleonix.biz/convergencemp/product-search.php

**Comment by bikash02** [comment]
@camerontrimble please check the above pages and leave your comment. 
push to live server?

**Comment by camerontrimble** [comment]
Approved. Push to live

**Comment by bikash02** [comment]
uploaded to live server.
