### ISSUE TITLE
Add text to make check out process more clear

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#212]
In the purchase process, after the buyer first goes to the shopping cart and selects the items to buy, then buyer is then sent back to the find songs page.  The buyer then has to find the small shopping cart icon on the upper right corner to continue the check out process.  Many people do not see this and tell me they have been sent back to the find songs page and can't continue.  Please put the text,

"Click here to continue checkout" in the banner area of the page to make it obvious to people how to continue to complete their purchase

**Comment by bikash02** [comment]
@i-puspita @debajyotiGuha please add a popup notification when someone click on "add to cart"

**Comment by i-puspita** [comment]
Design section is updated

**Comment by camerontrimble** [comment]
I don't see this on either the live site or the test site.

**Comment by bikash02** [comment]
@debajyotiGuha where are you on this issue?Please give me an update.

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 
Test server link:  http://cleonix.biz/convergencemp/product-listing.php

**Comment by bikash02** [comment]
@BryanCMP @camerontrimble we have updated and please try to add the product to the cart.
If anything else you update please let me know.

**Comment by camerontrimble** [comment]
Approved. Push to live server. @BryanCMP jump in if you have any issues.

**Comment by bikash02** [comment]
Uploaded to live server.
