### ISSUE TITLE
Search bars not working

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#213]
I just tried to find a song by name and the search process is not working at all

**Comment by Designer-cleonix** [comment]
@bikash02 Please resolve this ASAP.

**Comment by bikash02** [comment]
@creating-bubai Please check the issue.

**Comment by debajyotiGuha** [comment]
Updated in  http://cleonix.biz/convergencemp/product-search.php. Please check once. Only after approval it will changed in live server.

**Comment by camerontrimble** [comment]
Tested. Push to live and close the issue.

**Comment by bikash02** [comment]
uploaded to live server..
