### ISSUE TITLE
Make free download possible without needing to enter Credit Card information

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#214]
We have a free download of materials called "We Stand With Love."  At this point people cannot get this without having to enter their credit card information.  We want to make if very easy and quick for people to download free items like this without having to enter financial information.

**Comment by Designer-cleonix** [comment]
@bikash02 Do the needful.

**Comment by debajyotiGuha** [comment]
Updated in  http://cleonix.biz/convergencemp/payment.php. Please check once. Only after approval it will changed in live server.
Use promo code: Oa6wo6Nl to have 100% discount.

**Comment by camerontrimble** [comment]
In my test, when I did the guest checkout and pressed submit, the screen went to a blank white screen. I hit refresh and it then took me to back to the payment page where I would have to start over.

**Comment by camerontrimble** [comment]
I just tested again on the live server: https://convergencemp.com/payment.php. This is not working at all...which means that people can't make purchases on our site. Guys - that is absolutely unacceptable! You cannot push changes to the live server and not test them. These kinds of errors cost us customers and hurts our reputation.

**Comment by bikash02** [comment]
I have checked the issue and @debajyotiGuha you did a mistake over here.The user can't access directly to the payment page.Generally they will reach the page after adding something to the cart and proceed to checkout.So please stop accessing the payment page directly.

**Comment by Designer-cleonix** [comment]
@debajyotiGuha  Be more conscious and focused when you are working. This is not acceptable in future.

**Comment by bikash02** [comment]
@camerontrimble please check the link http://cleonix.biz/convergencemp/product-listing.php
and use promo code: Oa6wo6Nl to get 100% discount.
Note: If you selected the product license price it will not get any effect so please select " no license option" and apply the promo code and proceed to make payment.

**Comment by bikash02** [comment]
Waiting for your approval to make it live.

**Comment by camerontrimble** [comment]
Approved. Push updates to live server
