### ISSUE TITLE
Screen on Product View does not go completely to the right side

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#215]
![screen shot 2016-10-31 at 7 19 34 am](https://cloud.githubusercontent.com/assets/22161192/19853988/8934e55e-9f3a-11e6-9414-394ffc8a78c6.png)

I explained this to Debdip and he said to send a screen shot of the issue.  On my MAC especially (the problem exists on my PC also but to a lesser degree) I can't go all the way to the right side of the page to select the options that enable me to get back into a product to edit it.

**Comment by Designer-cleonix** [comment]
@bikash02 Please consult with Debdip, and if there is a responsive issue , please let me know.

**Comment by bikash02** [comment]
@creating-bubai Please put "uploaded by" and "email ID" in a same column and check the layout on MAC

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 .
http://cleonix.biz/convergencemp/backoffice/product-view.php

**Comment by camerontrimble** [comment]
Push to live server and close the issue

**Comment by bikash02** [comment]
updated
