### ISSUE TITLE
Add card to promote upcoming event on home page (URGENT!)

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#216]
I will send the card and the links to the registration for an upcoming event on email and Skype to Debdip.  It is urgent that this be added to our site (where the OPEN retreat event that has already happened currently is seen) before tomorrow (Tuesday, Nov. 1), because promotion for this event will begin Nov. 1 with an email campaign and we want people to be able to register.

**Comment by Designer-cleonix** [comment]
@debdiproy @bikash02 Do the needful ASAP.
