### ISSUE TITLE
Fix date and time column in the Order view in Backoffice

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#217]
Please fix this so that the orders can be viewed with the most recent order listed first and then in descending order according to date.

**Comment by debajyotiGuha** [comment]
Updated in  http://cleonix.biz/convergencemp/backoffice/order-details.php. Please check once. Only after approval it will changed in live server.

**Comment by camerontrimble** [comment]
Push to live server and close issue

**Comment by bikash02** [comment]
uploaded to live server.
