### ISSUE TITLE
Remove banner for OPEN event and replace with Convergence Music, Worship, and Liturgy

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#218]
Just a reminder that we need to have the graphic card that was sent for the Feb. 7-10, 2017 event on the Home Page instead of the OPEN event which already took place.  This new card should link to information about the event and to registration options.  All of this information was emailed to Debdip on 10/31/16.

**Comment by bikash02** [comment]
updated the banner.
https://www.convergencemp.com/index.php
