### ISSUE TITLE
Please update the query or add pagination to stop loading all the products in view page when someone try to access the page

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/Convergence-Music-Project#219]

**Comment by bikash02** [comment]
@debajyotiGuha & @creating-bubai  please check and resole the issue asap.
path: backoffice/product-view.php

**Comment by creating-bubai** [comment]
Product view page pagination added.
Please check product view page
Test server link:  http://cleonix.biz/convergencemp/backoffice/product-view.php

**Comment by bikash02** [comment]
Please create a column "Product" and merge "product image and title" into it.
display the data according to the date.

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 
Test server link: http://cleonix.biz/convergencemp/backoffice/product-view.php

**Comment by bikash02** [comment]
@i-puspita please format the column product.

**Comment by i-puspita** [comment]
Updated.Please Check.

**Comment by bikash02** [comment]
@i-puspita please check the attached file
![screenshot-cleonix biz 2016-11-04 14-52-26](https://cloud.githubusercontent.com/assets/16361011/20000628/72146c7a-a29e-11e6-81ba-8dd4a8bb60c2.png)
Format the email

**Comment by i-puspita** [comment]
Updated.Please Check.

**Comment by bikash02** [comment]
@camerontrimble Please check the page and waiting for your approval.
http://cleonix.biz/convergencemp/backoffice/product-view.php

**Comment by camerontrimble** [comment]
Approved. Push to live server

**Comment by bikash02** [comment]
uploaded to live server.
