### ISSUE TITLE
We need a way to edit the quantity of a product from the shopping cart

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#220]

**Comment by debdiproy** [comment]
Need to discuss, for example if we edit the quantity of a song then what will happen to the license.

**Comment by camerontrimble** [comment]
Let's make the license an attribute feature. Please discuss this concept with @debdiproy

**Comment by Designer-cleonix** [comment]
@bikash02 please finish this issue ASAP.

**Comment by Designer-cleonix** [comment]
@bikash02 what is the progress ?

**Comment by bikash02** [comment]
@camerontrimble @debdiproy This is a custom shopping cart solution and we can't add the license as an attribute feature of a product.I have checked the code and It will take too much time to reconfigure the whole system.Either we have to skip or build up the cart system from the scratch..
