### ISSUE TITLE
When a customer abandons their cart, we should still remember what products were there and keep it in the cart when they are logged in

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#221]

**Comment by debdiproy** [comment]
For this we need to alter the Database structure. Infact it will be good if we can have a call on this.

**Comment by camerontrimble** [comment]
Please put this into the development timeline.

**Comment by Designer-cleonix** [comment]
@bikash02 is it in development timeline ?

**Comment by bikash02** [comment]
Sorry for the delay!
We are trying our best and hope you'll get it resolve before on Friday.We were developing the site in custom solutions rather than using a framework.We have to reconfigure the custom shopping cart and hardcoded on it.

@creating-bubai @debajyotiGuha Please update the issue before on Friday.

**Comment by bikash02** [comment]
@creating-bubai please migrate the code from your remote pc to development server.
Thank you!!

**Comment by creating-bubai** [comment]
It will be updated tomorrow.

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 @debdiproy 
Link:      http://cleonix.biz/convergencemp/product-listing.php

**Comment by bikash02** [comment]
@camerontrimble @BryanCMP Please check in development server and Once you'll approve we'll migrate the file to live server.
http://cleonix.biz/convergencemp/product-listing.php

**Comment by Designer-cleonix** [comment]
@rikalively @amyolrick  Please check this feature and let us know so that we can make it live

**Comment by rikalively** [comment]
This feature is working! Thank you!
