### ISSUE TITLE
Formating issues on the purchase confirmation email

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#222]
Remove space between last paragraph and Bryan's name
Fix ' issues in his signature
Align paragraphs
Add a link in the text "log back into the site" that directs them back to the site. 

![screen shot 2016-11-03 at 11 46 55 am](https://cloud.githubusercontent.com/assets/15096099/19973333/4af92fd8-a1bb-11e6-9a37-664a3c7b1364.png)

**Comment by i-puspita** [comment]
updated

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 .
Use promo code: Oa6wo6Nl to have 100% discount and please select " no license option".
Test Server Link: http://cleonix.biz/convergencemp/product-listing.php

**Comment by bikash02** [comment]
@camerontrimble please check in the test server and let me know your feedback.
Once we get the approval we'll make it live.

**Comment by camerontrimble** [comment]
Approved. Push to live

**Comment by bikash02** [comment]
uploaded to live server.
