### ISSUE TITLE
Send a CC email copy to Bryan with the automatic email sent to customer after they purchase Early Adopter Membership

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#224]
Please copy Bryan (bryan@convergencemp.com) on the automatic email message sent to people when they buy the Early Adopter Membership so that Bryan will know they have received this.

**Comment by creating-bubai** [comment]
Updated.
Please check @bikash02 
Test server link:  http://cleonix.biz/convergencemp/eam.php
CC Mail Id for test server bikash@cleonix.com
For testing use promo code: SPE16CMP for 100% discount innto subscribe page
Link:  http://cleonix.biz/convergencemp/subscribe.php

**Comment by creating-bubai** [comment]
2nd cc mail id for test server bubai@cleonix.net

**Comment by bikash02** [comment]
Please check the page  http://cleonix.biz/convergencemp/eam.php
A copy will send to bryan@convergencemp.com & bsirch@sirchio.com

Waiting for your approval to push in the live.

**Comment by camerontrimble** [comment]
Approved. Push to live
