### ISSUE TITLE
Create Archive tab for downloads on Dashboard for downloads older than 30 days

### ISSUE THREAD

**Issue by BryanCMP** [ConvergenceUS/Convergence-Music-Project#225]
We don't want the dashboards to get too cluttered, especially for Early Adopter Members who will have 15 songs there initially and then the 5 additional bundles they purchase.  Debdip suggested creating an archive file and a note that explains that songs on the dashboard will be sent automatically to the archive tab after 30 days.

This is not an urgent issue and can wait if other things are more pressing.

**Comment by creating-bubai** [comment]
Updated.
Plese check @bikash02 @debdiproy 
Test server link:  http://cleonix.biz/convergencemp/archive.php
After 30 days of purchase downloadables product goes My Downloadables to Archive

**Comment by bikash02** [comment]
@BryanCMP @camerontrimble please check the new module.We have already checked and its working.
Waiting for your approval to push the file in live server.

**Comment by camerontrimble** [comment]
Approved. Push to live
