### ISSUE TITLE
Promo codes are not working

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#226]
I've tried two different discount codes, I get the same message that they are invalid.
<img width="717" alt="screen shot 2016-11-07 at 12 51 46 pm" src="https://cloud.githubusercontent.com/assets/23104131/20069081/173cc50c-a4e9-11e6-96d2-d9a68604a81d.png">

**Comment by bikash02** [comment]
where you testing development or production server?

**Comment by bikash02** [comment]
@creating-bubai Please check the promo code and give me an update.

**Comment by rikalively** [comment]
@bikash02 I wanted to make sure everything downloaded right and that I could access all the files.

**Comment by creating-bubai** [comment]
Promo code oqkwJgSt limit given 0 thats why not working.Now promo code oqkwJgSt limit updated into 100.
Please check once again in test server.
http://cleonix.biz/convergencemp/product-listing.php

**Comment by rikalively** [comment]
I do not have a valid login for the test server.
I tried on the live website and the promo code does not work.

**Comment by creating-bubai** [comment]
Updated.
Please check once again in live server.

**Comment by rikalively** [comment]
The promo code reduces the price to a negative number so it won't let me checkout. 

<img width="740" alt="screen shot 2016-11-08 at 9 24 34 am" src="https://cloud.githubusercontent.com/assets/23104131/20102740/324fb7d0-a595-11e6-9608-de7d5b43fc78.png">

<img width="756" alt="screen shot 2016-11-08 at 9 22 23 am" src="https://cloud.githubusercontent.com/assets/23104131/20102697/07b88df8-a595-11e6-8cfa-c3b337315606.png">

**Comment by creating-bubai** [comment]
Can you please check once again in live server and tell me if anything wrong it will be updated tomorrow.

**Comment by rikalively** [comment]
The promo code is working! Thank you.
