### ISSUE TITLE
Cannot download audio file

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#227]
When I click on the download button, I get sent to a page where I can listen to the song - but I cannot actually download it. 
<img width="687" alt="screen shot 2016-11-09 at 9 40 19 am" src="https://cloud.githubusercontent.com/assets/23104131/20141911/98ff72ec-a660-11e6-8417-ac5f18dc63f6.png">
<img width="1440" alt="screen shot 2016-11-09 at 9 39 33 am" src="https://cloud.githubusercontent.com/assets/23104131/20141917/9d291b66-a660-11e6-94a9-d9e3d3a8d1bb.png">

**Comment by creating-bubai** [comment]
Test server all page download button working.
Test Server Link:  http://cleonix.biz/convergencemp/bundle-music-download.php?ref=MTM0
Can you please give me the page link?

**Comment by rikalively** [comment]
I do not have login credentials to the test server. Here is the link to my download page https://www.convergencemp.com/music-download.php?ref=Mjc0

**Comment by bikash02** [comment]
I have checked the same link in live server and its working for both chrome & firefox.It might be the issue in Safary browser.So please check your browser version and if required then please upgrade the version or install the latest version.

**Comment by bikash02** [comment]
Please let me know if you are facing the problem only in safari

**Comment by rikalively** [comment]
It is an issue with safari - but I have updated and I still cannot download.

**Comment by rikalively** [comment]
Have we been able to find a way to download on safari?

**Comment by bikash02** [comment]
I was tried my level best and added some manual code and its not working in safari.Please allow me for one day more if will find a way.Thank you!!

**Comment by rikalively** [comment]
Let me know when you want me to try again @bikash02 
Thank you!

**Comment by bikash02** [comment]
Finally I resolved the issue.Please check the link.

**Comment by rikalively** [comment]
It will let me download but all I'm getting is a blank file. There is no audio file.

**Comment by bikash02** [comment]
@rikalively @debdiproy Please make a skype call to get it resolve.
I have tested in safari it's working for me.

**Comment by debdiproy** [comment]
@rikalively  I have already tested it using my mac and safari and this is getting downloaded for sure can you flush your browser cache and retest it. Thanks

**Comment by rikalively** [comment]
I am able to download it but it's not a file you can open. It's just a blank file. I am unable to Skype today because I am at my other job - sorry. 
<img width="610" alt="screen shot 2016-11-18 at 10 12 41 am" src="https://cloud.githubusercontent.com/assets/23104131/20434829/aeec57a0-ad77-11e6-9f62-64df8f951afc.png">

**Comment by debdiproy** [comment]
@rikalively I have resolved the issue and able to download the song both in Windows and Mac using Safari, Chrome and Firefox.
