### ISSUE TITLE
Not able to purchase early adopter membership

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#229]
I just got a message that a church is having an issue with purchasing the early adopter membership. This is the message they sent me:

Ebenezer UCC in Sheboygan WI registered On October 19th to be an Early Adopter Member. This shows up in our account with you as a pending order pending payment.. This is order CMP04204550. When I entered the information for payment, the screen accepted my credit card information but then did not actually record the payment.Our credit card has not been charged yet.  I have not been able to get back to the payment page in order to attempt payment again. Should I order again or is there some way for us to get to the payment page? Or is there some other way to pay? We're anxious to start using your service. Our username is ebenezeruccav.

How long will it take to fix this issue? I'd like to give them an idea of how long they will have to wait.

Thank you!

**Comment by creating-bubai** [comment]
You should purchase again Early Adopter Membership.

**Comment by rikalively** [comment]
I will tell him to purchase the membership again. What was the problem and is it fixed?

**Comment by amyolrick** [comment]
I am trying now to go in and purchase an Early Adopter Membership myself to test the system. As I try to checkout as a guest I am unable to edit the password field. I get a password error message and then all the other fields are inaccessible--they cannot be clicked. I will re-try this purchase by starting this process again, but please look into what is going on here.

![screen shot 2016-11-19 at 12 06 51 pm](https://cloud.githubusercontent.com/assets/22732566/20457065/2c9c10b2-ae51-11e6-880e-0131bcf67b1a.png)

**Comment by creating-bubai** [comment]
Updated.
Can you please check once again at test server and once you'll approve we'll migrate the file to live server.
http://cleonix.biz/convergencemp/product-listing.php

**Comment by bikash02** [comment]
uploaded to live server.
