### ISSUE TITLE
Early Adopter No Music

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#230]
We are still having issues with the Early Adopter Membership. Bryan just got this report from another client:

Hi Bryan, 
 
I just subscribed (on behalf of Galileo Church) to be a CMP Early Adopter. When I logged into my account to download I got the message "There is no free music to download. Click here to subscribe early adopter membership." Just wanted to let you know that there seems to still be a glitch.
 
Peace,
 
Paul

How quickly can we fix this issue?

**Comment by bikash02** [comment]
I will check the system data and get back to you soon with update.

**Comment by bikash02** [comment]
It will be very helpful if you provide me the username or email id for that account.

**Comment by amyolrick** [comment]
Paul Demer is the person reporting the problem, and his email is pdemer11@gmail.com

**Comment by rikalively** [comment]
Check  pauldemermusic@gmail.com
That's the email he used to create the account

**Comment by bikash02** [comment]
Please tell him to log into the account and he will be able to get the music now.

**Comment by rikalively** [comment]
This was his message back to me: I just tried to download the music files and they all seem to be in some kind of text file format - not an audio file... 

I was also having this issue with not being able to download music. How are we resolving this?

**Comment by debdiproy** [comment]
@rikalively I have resolved the issue and I am able to download the song in Firefox, Chrome and Safari I even tested it in a Mac. LI checked using Mr Paul account as well.
