### ISSUE TITLE
Text formatted incorrectly in emails

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#234]
@bikash02 
Bryan just emailed me. It looks like this is still an issue.
<img width="1041" alt="screen shot 2016-11-25 at 1 46 39 pm" src="https://cloud.githubusercontent.com/assets/23104131/20633586/693688b2-b316-11e6-8278-df78b4e23e95.png">

**Comment by bikash02** [comment]
@creating-bubai " &apos " doesn't get recognized on outlook.
I suggest that this gets changed to "&#8217" which is the equivalent and works across all mail clients.

**Comment by creating-bubai** [comment]
Updated.
@bikash02 please check at test server .
http://cleonix.biz/convergencemp/eam.php

**Comment by bikash02** [comment]
@rikalively Can I push it to live server?

**Comment by rikalively** [comment]
Looks good. Go ahead @bikash02

**Comment by bikash02** [comment]
uploaded to live server.
