### ISSUE TITLE
EAM Code does not work

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#235]
The code CEAM2016 for early adopter members to download free music is not working. I just tried using the code and this is the issue I received 
<img width="673" alt="screen shot 2016-12-19 at 1 13 20 pm" src="https://cloud.githubusercontent.com/assets/23104131/21323818/2b81e2d4-c5ed-11e6-8fbe-c8635058f377.png">

How quickly can we resolve this?

This is the email Bryan sent me:
The issue with the Early Adopter Members using the code  (CEAM2016) to get their additional 5 songs at no charge is still not working.  I just tried it myself and it did not work.  The person who contacted me about this last week, Jason Fairbanks, just emailed again saying he is unable to download this successfully.
 
Let’s please resolve this issue.  Let me know what if anything you need from me to proceed.  If you once again test this successfully then let’s share a screen and do it together so that I can do the same with people having trouble. 
 
Is it possible for people to use this code without having to enter their credit card information?  Seems like an unnecessary step since they have already paid for these 5 songs bundles with their Early Adopter Membership purchase.
 
This is high priority to fix

**Comment by debdiproy** [comment]
@rikalively This issue seems that the code was used by the same person for more than 1 time so please clarify if that is the case also give us the member username.

**Comment by rikalively** [comment]
I will check with Bryan. This should be the email for the account - pastorjason@lakeworthchurch.org

**Comment by rikalively** [comment]
I'll check with Bryan!

**Comment by bikash02** [comment]
We have resolved the issue on 21st Dec 2016. I checked the database and there was no data in the "user_coupon_mapping" table. So please try once again and let us know the result.We already tested on the development server and it was working.

If the subscriber still trouble getting used to the coupon code please let us know.

**Comment by rikalively** [comment]
<img width="672" alt="screen shot 2016-12-27 at 9 54 45 am" src="https://cloud.githubusercontent.com/assets/23104131/21502062/18e3edd2-cc1b-11e6-810e-6a53b4ca3993.png">

I just tried this and it gave me this error. The account I used is an early adopter member but it gave me this message. The account email is rika+1@skycrossmedia.com

**Comment by bikash02** [comment]
@rikalively @debdiproy I have tested using your account by altering the password temporarily.I applied the coupon code "CEAM2016" and its working fine.Here is the order id CMP44434596

![success](https://cloud.githubusercontent.com/assets/16361011/21520494/ab81ebf8-cd1a-11e6-860f-e050f100f536.png)

Please login into the system and you will able to get more about the order details.

One more thing If you'll try using the same coupon code you not able to purchase because coupon code - Limit to 1 time per subscriber or EAM.So please check the system very carefully and let us know when you're ready to go live and then we'll truncate the last data.

**Comment by rikalively** [comment]
I just made a new account and purchased EAM using this link - https://www.convergencemp.com/subscribe1.php
I tried the coupon and got the same error message as before? I'm using a different email every time so it should be a different account. Why am I having this issue?

**Comment by bikash02** [comment]
Resolved the issue.Please check using the same link.

**Comment by rikalively** [comment]
Thank you!
