### ISSUE TITLE
Customer not receiving EAM emails

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#236]
We have a customer who purchased an Early Adopter Membership - his order was marked and he was billed but he has not received any follow-up emails from us. We need to register him as an Early Adopter Membership and send him all of those EAM emails. 

How soon can we resolve this?

This is the email Bryan sent me:
Hi everyone,

You can read this message chain, but here's the problem;

Jason Fairbanks (pastorjason@lakeworthchurch.org) says he joined CMP as an Early Adopter Member on 9/19/16.  I remember seeing his order marked as pending in the back office.  He was billed (see PayPal receipt he sent).  But he never received any follow up email from us at all, and when Debdip and team recently went through these pending sales to sort out the completed from the pending they must not have seen this order completed.  It is no longer in the order records in the back office.

We need to register him as a paid Early Adopter Member and send him the follow up email.

**Comment by rikalively** [comment]
What's happening with resolving this issue?

**Comment by bikash02** [comment]
Updated the user to Early Adopter Member.
Please ask him to check "pastorjason@lakeworthchurch.org" an email send to his inbox regarding updating the password.

**Comment by bikash02** [comment]
Follow up mail also sent to registered email id

**Comment by bikash02** [comment]
Any update?

**Comment by rikalively** [comment]
Haven't heard back from anyone - but I'll assume there is no problem.
