### ISSUE TITLE
Cart does not save

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#237]
<img width="1417" alt="screen shot 2016-12-30 at 12 31 08 pm" src="https://cloud.githubusercontent.com/assets/23104131/21569586/1968ae78-ce8c-11e6-8465-defa3981b115.png">
On this page, if you hit "make payment" and maybe forgot to do something (like add the promo code); if you hit back, you lose what is in your cart. Can we change this so it saves what is in the user's cart?

**Comment by bikash02** [comment]
We have updated the code.

**Comment by rikalively** [comment]
Great! Thank you
