### ISSUE TITLE
Customer not receiving emails

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#238]
Bryan just sent me this message. Same as before, a customer is not receiving a receipt or any follow-up emails:

Also, I just got a message from Terry Overfelt toverfelt@broadwaychristian.net.  She joined as an EAM on Dec. 8 and did not receive a receipt for her payment or the follow up email from us.  Yet she is marked paid and completed in the back office.  Please see that her order was completed and make sure she gets the receipt and the follow up email.

Thanks,
Bryan

**Comment by bikash02** [comment]
Please login into the admin panel and click on "Orders" search the customer order details and click on the email icon.Once you'll hit on the icon an email send to the registered email id.

**Comment by rikalively** [comment]
Thank you!
