### ISSUE TITLE
Discount code not working

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#240]
A customer is trying to use the discount code OPEN25 for the CMP Live Event and he cannot get it to work nor can I. 

This is the link https://xb323.infusionsoft.com/app/manageCart/showManageOrder

**Comment by bikash02** [comment]
As per my knowledge discount code OPEN25 is not relevant to https://www.convergencemp.com website.I didn't find the code in backoffice.So please explain where you should apply the coupon code.We don't have access of infusionsoft.You should create the coupon code where your infusionsoft order form is hosted.

**Comment by rikalively** [comment]
Okay - thank you.

**Comment by camerontrimble** [comment]
This should be fixed. Please test @rikalively

**Comment by rikalively** [comment]
Working now! Thank you!
