### ISSUE TITLE
Comments/Ratings not working

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#241]
A customer has been trying to review the songs on the site and they are not showing up when submitted. The star rankings nor the comments are working. Also, the message says "reating" rather than "rating". Please fix the spelling. 

Thank you!

**Comment by bikash02** [comment]
@debajyotiGuha Please fix the spelling.

**Comment by bikash02** [comment]
@rikalively Once the review data will get approve from the system admin then it will show in the website otherwise you won't able to get the data.

**Comment by debajyotiGuha** [comment]
Rating spelling updated.

**Comment by camerontrimble** [comment]
Bryan has to approve all comments/rating. @rikalively you might need to remind him of that.

**Comment by rikalively** [comment]
Okay! Thanks
