### ISSUE TITLE
Submitting a comment takes you to blank page

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#242]
Bryan has received multiple messages from people saying that when they try to submit a comment/rating on a song, it takes you to a blank page. 
If you try again, it will go through. Can we fix this?

Also, submitted is spelled incorrectly. Please change submited to "submitted"

**Comment by debdiproy** [comment]
@bikash02 Check and resolve this by today

**Comment by debajyotiGuha** [comment]
Updated.

**Comment by rikalively** [comment]
Thank you!

Also, submitted and successfully are spelled incorrectly. Change from "submited" to "submitted" and 
"succesfully"to "successfully"

**Comment by rikalively** [comment]
@BryanCMP  reported that customers are still having issues posting comments. Sometimes it works and sometimes it doesn't. We need to find a way to make this consistent.

**Comment by bikash02** [comment]
I have tested personally and its working for both blog comment and product comment & rating.So if you explain what kind of error the customers were facing then it'll be more easier to fix the issue.We have tested the page for IE,firefox & chrome as well.

Note: {If the comment /Rating wasn't approved by the admin it will not publish in the website.}

**Comment by rikalively** [comment]
The comment page just seems to be unpredictable - sometimes it works and sometimes it doesn't - it's not consistent. Have you tested it for Safari?

Also, maybe in the message that says, "Your review and rating submitted successfully" we can change it to "Your review and rating pending approval" so people understand that it won't show up right away.

**Comment by debajyotiGuha** [comment]
Updated
