### ISSUE TITLE
Customer did not receive membership

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#244]
A customer named Doug Hammack had purchased the EAM and has not received any follow up emails or additional membership benefits. 

Here is the account information: 

user id:  northraleighcommunitychurch
pass:  nrcc55555

You paid $149.00 USD to Convergence Network, Inc.
1 x Early Adopter Membership(membership) $149.00 USD
Paid with Visa x-7287 $149.00 USD
Receipt number: 4239788490727786

**Comment by debdiproy** [comment]
Hello @rikalively  @camerontrimble @BryanCMP 

This can be possible that a customer did not receive an email and that is the reason why we have created the module to resend emails manually. in the back end.

**Comment by bikash02** [comment]
I have checked the customer details, upgraded the membership and the follow up email sent to registered email id.
