### ISSUE TITLE
Customer charged twice

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#245]
A CMP Early Adopter member named Elane O’Rourke says she was charged 2 times for the membership and would like to be reimbursed for the second one.
She joined on 1/5/17. 

Please reimburse her as soon as possible.

**Comment by bikash02** [comment]
I have reviewed the system including database and she joined on 2017-01-05. I didn't find any duplicate orders against her ID for the  Early Adopter membership.
Here is the order details
{Order id: CMP36417403} {Date: 2017-01-05 12:34:32} {Amount: 149}

So please clarify and let me know your feedback.

**Comment by bikash02** [comment]
any update?

**Comment by rikalively** [comment]
I have not gotten an update. @BryanCMP - any news on this issue?
