### ISSUE TITLE
Fix Customer Account

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#246]
Here’s another person who was charged for the Early Adopter Membership but never got things working:
 
Lisa Gaul
lgucchot@live.com

She said when she tried to sign in it was unsuccessful and when she tried "forgot password," she never got a return email.

**Comment by bikash02** [comment]
Did you get the payment from her?I checked the system and she created her account on 2016-10-18 02:25:02 as normal user.So please confirm then we'll upgrade her account to EAM .

**Comment by rikalively** [comment]
She did get a receipt from paypal. She should be a EAM user.

**Comment by bikash02** [comment]
Upgraded to EAM and follow up email sent to her id.
