### ISSUE TITLE
Customer paid by check - account needs to be active

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#247]
Jeffrey Lingle paid by check instead of credit to be an EAM. His email is pastor@epiphany-rockhill.org   
The check was sent to the Atlanta office along with all of the necessary information. We need to set him up as an EAM and get his membership going.  Please fix this as soon as possible.

**Comment by bikash02** [comment]
I will check the system and will give you update asap.

**Comment by bikash02** [comment]
I created an account for him and set him up as an EAM.Please ask him to follow the email  pastor@epiphany-rockhill.org

**Comment by bikash02** [comment]
Please keep me inform if any further payment is done by check as because we have only credit card option to pay.

**Comment by rikalively** [comment]
Thank you!
