### ISSUE TITLE
Update Customer Account

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Convergence-Music-Project#248]
Dwight Hein, who purchased an Early Adopter Membership on 10/31/16, has never received his follow up email and his membership is not yet active.
 
Please check into this and make sure he has everything he needs.  His email is pastor@salemucccampbelltown.org

Please make sure he’s good to go as an Early Adopter Member.

**Comment by rikalively** [comment]
Has this been resolved?

**Comment by bikash02** [comment]
Resolved.
