### ISSUE TITLE
http://convergencemp.com/subscription-service.php

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#28]
Need a way for people to purchase a subscription on this page. Also add a button on the "Find a song" page on the left side.

**Comment by bikash02** [comment]
@i-puspita please complete the design part first and I will take care the rest part.

**Comment by i-puspita** [comment]
design section is updated

**Comment by bikash02** [comment]
updated

**Comment by bikash02** [comment]
Please provide us the paypal id

**Comment by camerontrimble** [comment]
cameron@convergenceus.org

**Comment by bikash02** [comment]
updated the paypal id
