### ISSUE TITLE
Add subscription discount and coupon code

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#34]
Review all attachments that Bryan has sent to us

**Comment by bikash02** [comment]
updated discount and coupon code.Please create the coupon code from the backend first.
http://convergencemp.com/subscribe.php
http://convergencemp.com/cart.php

**Comment by camerontrimble** [comment]
We need to be able to connect a discount code to a particular product or to have the option for the code to be applied to all products.

**Comment by bikash02** [comment]
updated the code.
http://convergencemp.com/backoffice/coupon-add.php

**Comment by camerontrimble** [comment]
Add discount codes associated with Product categories and individual products

**Comment by bikash02** [comment]
Now you can add a coupon for product categories and as well as individual product.
