### ISSUE TITLE
Load Otis Moss endorsement

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#44]

**Comment by Designer-cleonix** [comment]
I have added the info and image in slider. but they are not loading. Fix it ASAP. @creating-bubai

**Comment by bikash02** [comment]
updated

**Comment by camerontrimble** [comment]
Please make the Otis Moss Slide the #2 slide in the banner

**Comment by bikash02** [comment]
updated
