### ISSUE TITLE
Connect Dashboard Widgets to real data in the system

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#5]

**Comment by debdiproy** [comment]
We have already added real time data in the dashboard widgets, please let us know if you need any further customization on that

**Comment by bikash02** [comment]
@jayantapatra please update the visitor map including map pointer in the dashboard section..

**Comment by jayantapatra** [comment]
updated this map. please check and give review

**Comment by bikash02** [comment]
Please respond
