### ISSUE TITLE
Add quote to front page

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#62]
Every movement needs new songs to sing. Convergence Music Project is a collaboration of musicians, artists, congregational leaders and denominations to curate and distribute beautiful congregational music with life-giving, progressive theology. We believe Jesus's life models love, grace and hope to everyone - absolutely everyone - and we want to sing songs that are true to our experience of this just and generous God. - Cameron Trimble

**Comment by bikash02** [comment]
updated
