### ISSUE TITLE
Can we use this image for the "Advertise here" box on the homepage? 

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#70]
![Uploading OPEN Faith Web+Banner+2.jpg…]()

**Comment by Designer-cleonix** [comment]
Updated

**Comment by camerontrimble** [comment]
![open faith web banner 2](https://cloud.githubusercontent.com/assets/15096099/15248315/86ee002a-18e7-11e6-87bc-63e8f3f5df5f.jpg)
