### ISSUE TITLE
Need a way for people to purchase - please add a button

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#71]
http://convergencemp.com/eam.php

**Comment by bikash02** [comment]
added the purchase button.

**Comment by camerontrimble** [comment]
Ummm...this looks unfinished. I'm assuming you are still working on the design? 
![screenshot 2016-05-14 10 12 04](https://cloud.githubusercontent.com/assets/15096099/15268905/769f842a-19bc-11e6-92fe-c6c7c08f54a7.png)

**Comment by camerontrimble** [comment]
I think you could just drop them into the shopping cart once they have submitted the music since we have a coupon code function already built. It would save having to create a whole new page, maybe...

In other words, make submitting a song a product that is purchased through the shopping cart

**Comment by camerontrimble** [comment]
Based on conversation with Debdip and Debarati, we are going to use the Shopping Cart functionality with a static price of $30 for song submission.

**Comment by camerontrimble** [comment]
Moved to next phase of development
