### ISSUE TITLE
Feature artist image disappeared from homepage - may be my fault! Sorry!

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#74]

**Comment by Designer-cleonix** [comment]
It's ok. No problem. We will fix it  but can you please tell me what did you do , then probably developers  can guide you to change the images or rectify the issue to avoid this problem in future. Thank you.

**Comment by camerontrimble** [comment]
I edited the text on the homepage through the backend. I didn't do anything to the image files. I saved the page and then the image disappeared.

**Comment by creating-bubai** [comment]
updated

**Comment by Designer-cleonix** [comment]
Hello @camerontrimble  ,
 Sorry to say, that was not your fault, that problem occurred due to a programming bug. But we have solved it.
