### ISSUE TITLE
Can we access the files in a directory through the backend?

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#75]

**Comment by bikash02** [comment]
You can access files in a directory through the backend.Please tell me what kind of access you need.
1.Files of all products.
2.Files of individual product.

**Comment by camerontrimble** [comment]
Individual products would be most important at this point. Bryan (the admin) will need to be able to download the files.

**Comment by Designer-cleonix** [comment]
@bikash02  Please take care of it. Thank you.

**Comment by bikash02** [comment]
You will find the link under Products-> Download Files.Only admin can view the link.
http://convergencemp.com/backoffice/product_directory-view.php
