### ISSUE TITLE
Licensing Box should pop up after a customer adds a song to their cart

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#76]
Add text in a pop up box ( Debdip has this in a word doc)

**Comment by Designer-cleonix** [comment]
@bikash02  
After clicking "add to cart" button, there will be a modal/pop up to select the following option with radio button

Your Licensing Options
1. ___ No licensing deal needed. My church has licensing for this song via CCLI or LicenSing or OneLicense.net or some other church music licensing organization.  We will report as usual.
2. ___I am a CMP Early Adopter Member or Subscription Service Member and am enjoying the great value of performance rights for worship services in my local church context being included in my membership fee.  
   Therefore I do not need an additional license to use this song during the year covered by my annual subscription payment.  I will however still report songs registered with other licensing organizations such as CCLI in the usual way.  There is no additional payment required if a CMP song is also listed with other church licensing organizations, and CMP encourages its writers to list their songs with other licensing organizations if they so desire.   Reporting simply increases the likelihood that songwriters will receive royalties for use of their songs.
3. ___ I need a one-time use license for this one song (use the song at one service or event. Permission included to print words in a bulletin or on projected slides). $10.00
4. ___ I need an ongoing license for this song for one year, which I can renew this time next year. $20.00 

Whether or not you need to purchase a song use license from the above options, PLEASE visit our site each time you use a CMP song in worship and register the use of the song by logging into your account and selecting the “we just worshipped with this song” option.  There is no additional charge for you to do this, but reporting your song use this way enables us to know which songs are being used most widely, to update our top ten list based on the most popular songs, and it encourages our songwriters and artists by letting them know their music is being used and enjoyed.  Thanks so much!

**Comment by bikash02** [comment]
updated

**Comment by camerontrimble** [comment]
Looks GREAT!

**Comment by Designer-cleonix** [comment]
Thank YOU...
