### ISSUE TITLE
Move the "License By" dropdown box to the back end so that an admin can enter that info...BUT...

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#77]
But still display the text on the product page on the front end so the customer can see it.

**Comment by bikash02** [comment]
updated

**Comment by camerontrimble** [comment]
With the new design, we will incorporate this into the table.

**Comment by camerontrimble** [comment]
I am wondering if we need to redesign the product table structure. We will have different kinds of products:

Music
License Fees
Submit Music
Membership

Right now, we can only load music. Do you see the problem?
