### ISSUE TITLE
Display Pricing needs to be edited

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#78]
Product Name
- Full Price
- Discount Price
- Member Price

Do this on both the "Find Songs" page and the individual product pages

**Comment by bikash02** [comment]
updated the issue.

**Comment by camerontrimble** [comment]
Great. One more thing: If there is not a price listed for Discount Price, that label should not appear on the Find a Song Page or the Product page. 

Also, on the product page, each product needs the price breakdown as well. Let's change the design on this section to make this more efficient. Let's build a table like this attached that lists all of the ways that a customer can purchase a product. 
![screenshot 2016-05-14 10 07 04](https://cloud.githubusercontent.com/assets/15096099/15268883/a48830ea-19bb-11e6-850f-c5630da7e82e.png)

**Comment by camerontrimble** [comment]
On this table, make the "Quantity" a toggle that they can select how many they want to purchase. That way you can remove the "select" column. 

Retail box should be: just the price - not the descriptions. I can imagine two ways:
1. We could have a small "Discount" icon appear when there is a discount price loaded in the system. We list only the discount price. 
2. We list the retail price with a slash through it and greyed out and then list the discount price. 

![screenshot 2016-05-16 16 08 52](https://cloud.githubusercontent.com/assets/15096099/15302356/8c2efdc8-1b80-11e6-92d2-7118b5b48d25.png)
