### ISSUE TITLE
Can we change the submit music process?

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#84]
Can we change the process to something more like this: https://www.lorenz.com/more-information/submit-your-music

The people submitting the music don't have to log in first. Right now, because people have to log in, it creates a barrier.

**Comment by bikash02** [comment]
updated the code.
kindly check and correct me if I'm wrong.

**Comment by bikash02** [comment]
Sorry the module was partially completed.After submitting the music files its redirect to payment page.But the page was functionally incomplete at this point of time.

**Comment by camerontrimble** [comment]
Just had a meeting with the client - they want to move the $30 fee to the next phase of development. So, make the song submission process free with no "add to cart" function.

**Comment by bikash02** [comment]
updated the code.
