### ISSUE TITLE
Need to edit the user section

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#86]
![screenshot 2016-05-16 16 19 03](https://cloud.githubusercontent.com/assets/15096099/15302645/fc3eeda2-1b81-11e6-9603-fbeaa0f3f169.png)

Remove Followers, Sales, Member
Hide the layout button in top right corner
Update the "Member Since date" of remove it
Hide Tasks
Hide messages - people don't need to email each other through the system

**Comment by bikash02** [comment]
updated the dashboard.
