### ISSUE TITLE
Format boxes on the dashboard

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#87]
Style this box
![screenshot 2016-05-16 16 25 18](https://cloud.githubusercontent.com/assets/15096099/15302840/0685659c-1b83-11e6-8d9f-5a86a5fffe8b.png)

**Comment by bikash02** [comment]
@creating-bubai  Please add placeholder image if the field is empty.

**Comment by creating-bubai** [comment]
Updated

**Comment by camerontrimble** [comment]
Remove Browser Usage box completely
