### ISSUE TITLE
Product List Page edits

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#90]
Change design once again. Remove the product price list under each image and instead list:

Song Title
Artist Name
Starting At (list the lowest price value)

**Comment by camerontrimble** [comment]
Just to make sure I was clear, we need these boxes edited
![screenshot 2016-05-20 08 15 30](https://cloud.githubusercontent.com/assets/15096099/15427453/3a4dd426-1e63-11e6-8fc9-66c2ea47bdc5.png)

**Comment by Designer-cleonix** [comment]
@debajyotiGuha  Please update me on this.

**Comment by debajyotiGuha** [comment]
Madam,
Bubai solved the issue and today morning the issue has been closed.
On Saturday 21 May 2016 09:35 PM, Debarati Bose Roy wrote:

> @debajyotiGuha https://github.com/debajyotiGuha Please update me on 
> this.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/ConvergenceUS/Convergence-Music-Project/issues/90#issuecomment-220785879

## 

Thanks and Regards
Debajyoti Guha
debajyoti@cleonix.net
