### ISSUE TITLE
When a product license expires, make the link to the product inactive

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#91]

**Comment by bikash02** [comment]
Can you please guide me how to implement this?
I think we have to add a product expiry date for individual product in the backend and admin will check and input the date value and once it cross the date limit it will automatically inactive and remove the product from the product list.

I'm waiting for your response.

**Comment by camerontrimble** [comment]
The expiration should be based on the date that the customer purchased the product. The actual product does not expire - just their access to the product.

**Comment by bikash02** [comment]
We have updated the issue.Once the license is expired, the product will not visible in the "My Account" page for the particular user or the customer.
