### ISSUE TITLE
On the Song Submit page, move the Lyric Sheet field to follow the Music File field

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/Convergence-Music-Project#94]

**Comment by bikash02** [comment]
updated

**Comment by camerontrimble** [comment]
Should be in this order:

First Name
Last Name
Email
COVER PHOTO
Song Name
Music Audio File By
MUSIC AUDIO FILE (.MP3) 
LYRIC SHEET (.PDF, .DOC, DOCX) 
LEAD SHEET (.PDF, .DOC, DOCX)
LEAD SHEET BY
PIANO ARRANGEMENT
**POWERPOINT (.PPT, .PPTX)** (NOTE  TO TEXT CHANGES HERE)

**Comment by bikash02** [comment]
Updated the display order.
Thank you.
